{
  "hash": "71f1dbe0f3fbf0af7490bc72fe07f9cf",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"FAA Airline Performance Analysis\"\nauthor: Jiahui Liu\nformat:\n  html:\n    theme: cosmo\n    code-fold: true\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nq1  <- read_csv(\"q1.csv\",  show_col_types = FALSE)\nq2  <- read_csv(\"q2.csv\",  show_col_types = FALSE)\nq3  <- read_csv(\"q3.csv\",  show_col_types = FALSE)\nq4  <- read_csv(\"q4.csv\",  show_col_types = FALSE)\nq5  <- read_csv(\"q5.csv\",  show_col_types = FALSE)\nq6a <- read_csv(\"q6a.csv\", show_col_types = FALSE)\nq6b <- read_csv(\"q6b.csv\", show_col_types = FALSE)\nq7  <- read_csv(\"q7.csv\",  show_col_types = FALSE)\n```\n:::\n\n\n\n## Introduction\n\nAir travel plays a critical role in modern transportation, connecting millions of passengers across cities every day. Understanding the factors that influence flight performance—such as delays, cancelations, and traffic patterns—is essential for improving operational efficiency, enhancing customer experience, and supporting data-driven decision-making within the aviation industry.\n\nIn this project, we analyze the Airline On-Time Performance dataset from November 2019, combining it with several dimension tables to enrich the information related to airlines, airports, distances, weekdays, and cancelation codes. By integrating these datasets, we uncover meaningful patterns in flight operations from both the airline and airport perspectives.\n\nOur analysis addresses a series of targeted questions:\n\n-   Which airlines experience the longest delays or the earliest departures?\n\n-   How does flight activity vary across days of the week?\n\n-   Which airports show the highest average delays, both overall and for each airline?\n\n-   Are cancelations common, and what are the most frequent reasons behind them?\n\n-   How do daily flight volumes change over time, and what trends emerge when using a moving average?\n\nThrough SQL queries, visualizations, and data-driven storytelling, we aim to provide a comprehensive overview of U.S. flight operations during this period. The findings highlight not only performance differences among airlines and airports but also broader structural patterns—such as demand cycles, congestion effects, and weather-related disruptions.\n\nThis project ultimately demonstrates the value of combining relational data analysis with visualization techniques to reveal insights that are both operationally relevant and intuitively understandable.\n\n## Full Data Story Version\n\nAir travel delays are often seen as random inconveniences, but our analysis shows they follow clear and measurable patterns. By studying flight performance in November 2019, we uncover how delays emerge from the interaction of four major forces: airline operations, airport congestion, weather disruptions, and passenger demand cycles.\n\nWe begin by comparing airlines and observe substantial variation—some carriers frequently experience extreme delays, while others maintain tighter schedules. These patterns reflect differences in fleet management, route networks, and operational resilience.\n\nLooking across days of the week, demand peaks sharply on Fridays, creating increased pressure across the entire aviation system. At the airport level, we find that certain airports consistently suffer the longest delays, driven by location, traffic volume, and weather exposure. For each airline, specific airports emerge as recurring bottlenecks, revealing where their network struggles the most.\n\nCancelation patterns reinforce this story: weather and carrier operational issues dominate across the busiest hubs. Meanwhile, the daily trend analysis shows that overall flight activity is stable, with only short-term dips during holiday and weather events—suggesting that disruptions are concentrated but predictable.\n\nTogether, these findings paint a coherent picture:\ndelays are not random—they are the product of interconnected operational, environmental, and structural factors.\nBy understanding these relationships, airlines and airports can better target improvements, and travelers gain a clearer view of what drives flight reliability.\n\n\n## Airline Performance Overview\n\n### Maximum Departure Delays\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nq1 %>%\n  ggplot(aes(x = reorder(Airline, Max_Departure_Delay),\n             y = Max_Departure_Delay)) +\n  geom_col() +\n  coord_flip() +\n  labs(\n    title = \"Maximum Departure Delay by Airline\",\n    x = \"Airline\",\n    y = \"Max departure delay (minutes)\"\n  )\n```\n\n::: {.cell-output-display}\n![](miniproject_files/figure-html/unnamed-chunk-2-1.png){width=672}\n:::\n:::\n\n\n\nThe chart above compares the maximum recorded departure delay for each airline in the dataset. The results show substantial variation across carriers. Hawaiian Airlines and Southwest Airlines have the lowest maximum delays, indicating relatively stable schedule performance with fewer extreme disruptions.\n\nOn the opposite end, airlines such as Allegiant Air, American Airlines, PSA Airlines, and SkyWest Airlines exhibit the highest maximum delays, in some cases exceeding 1,800 minutes (over 30 hours). These extreme outliers suggest operational or weather-related disruptions that significantly affected certain flights.\n\nWhile maximum delay is not representative of overall performance, it highlights which airlines experienced the most severe single-flight delays—a useful indicator of operational vulnerability during irregular events.\n\n### Maximum Early Departures\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nq2 %>%\n  ggplot(aes(x = reorder(Airline, Max_Early_Departure_Minutes),\n             y = Max_Early_Departure_Minutes)) +\n  geom_col(fill = \"darkgreen\") +\n  coord_flip() +\n  labs(\n    title = \"Maximum Early Departure by Airline\",\n    x = \"Airline\",\n    y = \"Early departure (minutes)\"\n  )\n```\n\n::: {.cell-output-display}\n![](miniproject_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n:::\n\n\n\nThe second chart examines the maximum amount of early departure time for each airline. Unlike delays, early departures can also negatively impact passengers—especially those arriving at the gate just before the scheduled departure time.\n\nSkyWest Airlines and Alaska Airlines show the largest early departures, with flights leaving more than 45 minutes early. Several other airlines—including Allegiant, Mesa, Spirit, PSA, and Frontier—also exhibit notable early departures of 25–35 minutes.\n\nIn contrast, airlines such as Envoy Air, Southwest, and American Airlines tend to have smaller early-departure extremes, suggesting tighter adherence to scheduled departure times.\n\nThese findings demonstrate that while delays often attract more attention, early departures are also a meaningful component of airline schedule reliability. Understanding both sides of schedule deviation provides a more complete picture of carrier performance.\n\n## Flight Activity by Weekday\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nq3 %>%\n  ggplot(aes(x = reorder(Weekday, Num_Flights),\n             y = Num_Flights)) +\n  geom_col(fill = \"orange\") +\n  coord_flip() +\n  labs(\n    title = \"Total Flights by Weekday\",\n    x = \"Day of the Week\",\n    y = \"Number of Flights\"\n  )\n```\n\n::: {.cell-output-display}\n![](miniproject_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n:::\n\n\n\nThe chart displays the total number of flights for each day of the week. The results indicate that Friday is the busiest day, with the highest overall flight count. This aligns with typical travel patterns, as both business and leisure travelers frequently fly at the end of the workweek.\n\nSaturday and Monday follow closely behind, suggesting strong weekend and early-week travel demand. Meanwhile, Thursday, Tuesday, and Sunday show moderately lower but still substantial flight volumes.\n\nInterestingly, Wednesday and Sunday have slightly fewer flights compared to other days, which may reflect a dip in both business and leisure travel activity mid-week and at the end of the weekend.\n\nThese patterns help contextualize delay and cancelation trends observed in later sections of the analysis, as higher flight volume often corresponds to increased operational pressure on airlines and airports.\n\n## Airport Delay Analysis\n\nHaving understood delays by airline and weekday patterns, we now investigate whether specific airports consistently contribute to delays.\n### Worst Airport Overall\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nq4\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 3\n  Airport_Name                     Airport_Code Avg_Departure_Delay\n  <chr>                            <chr>                      <dbl>\n1 Eagle, CO: Eagle County Regional EGE                         61.8\n```\n\n\n:::\n:::\n\n\n\nThe analysis identifies Eagle County Regional Airport (EGE) as the airport with the highest average departure delay, at approximately 61.8 minutes per flight. Even after treating early departures as having zero delay, EGE still stands out significantly compared to all other airports.\n\nThis result suggests that structural or environmental factors unique to this airport—such as weather constraints, mountain geography, or limited runway capacity—may contribute to persistent delays. EGE’s elevated delay level makes it a critical point of inefficiency in the overall flight network.\n\n### Worst Airport for Each Airline\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nq5 %>%\n  ggplot(aes(x = reorder(Airline_Name, Avg_Departure_Delay),\n             y = Avg_Departure_Delay)) +\n  geom_col(fill = \"red\") +\n  coord_flip() +\n  labs(\n    title = \"Airport with Highest Avg Departure Delay for Each Airline\",\n    x = \"Airline\",\n    y = \"Average delay (minutes)\"\n  )\n```\n\n::: {.cell-output-display}\n![](miniproject_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\n\n\nThe chart below shows the airport where each airline experiences its highest average departure delay. This analysis highlights operational “pain points” specific to individual carriers.\n\n-   SkyWest Airlines (OO) and Envoy Air (MQ) face particularly severe delays at their worst airports, averaging over 230 minutes—substantially higher than others. This suggests operational dependencies on congested or weather-sensitive airports.\n\n-   Airlines such as Southwest (WN) and Hawaiian (HA) show relatively small maximum averages, indicating that their worst airports still perform reasonably well.\n\n-   The variation across airlines highlights important differences in:\n\n    -   route networks\n\n    -   regional operating environments\n\n    -   airport partnerships or hubs\n\n    -   fleet characteristics\n\nUnderstanding these pain points may help airlines optimize scheduling or allocate operational resources more strategically.\n\n## Cancelation Analysis\n\n### Are Flights Canceled?\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nq6a\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 1\n  Num_Canceled_Flights\n                 <dbl>\n1                 4446\n```\n\n\n:::\n:::\n\n\n\nOur dataset confirms that cancelations do occur. A total of 4,446 flights were canceled during the study period.\n\nWhile this represents only a small fraction of all flights, the presence of thousands of cancellations indicates that operational disruptions—whether caused by the airline, external systems, or weather—are a non-negligible factor in overall performance.\n\n### Most Frequent Cancelation Reason per Airport\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nq6b_top15 <- q6b %>%\n  arrange(desc(Num_Cancellations)) %>%\n  slice(1:15)\n\nq6b_top15 %>%\n  ggplot(aes(x = Num_Cancellations,\n             y = reorder(Airport_Name, Num_Cancellations),\n             fill = Most_Frequent_Reason)) +\n  geom_col() +\n  labs(\n    title = \"Top 15 Airports by Cancellations\",\n    x = \"Number of cancellations\",\n    y = \"Airport\",\n    fill = \"Reason\"\n  ) +\n  scale_x_continuous(breaks = scales::pretty_breaks(5)) +\n  theme_bw(base_size = 12) +\n  theme(\n    plot.title      = element_text(hjust = 0.5, size = 14),\n    axis.text.y     = element_text(size = 8),\n    legend.position = \"bottom\"\n  )\n```\n\n::: {.cell-output-display}\n![](miniproject_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n\n\nTo better understand cancellation patterns, we identify the most common cancelation reason at each airport, and then highlight the **Top 15 airports with the highest number of cancellations.**\n\nThe visualization shows that:\n\n-   **Weather-related cancellations** dominate several major airports—especially Chicago O’Hare (ORD) and Denver (DEN), which experience significant seasonal weather challenges such as snowstorms and low visibility.\n\n-   **Carrier-related issues** (e.g., staffing shortages, mechanical problems, or internal disruptions) are more common at busy hubs like Los Angeles (LAX), Dallas/Fort Worth (DFW), and Charlotte (CLT).\n\n-   Airports with the highest cancellations tend to be large national hubs, which face both heavy traffic volumes and complex operational constraints.\n\nOverall, the analysis suggests that:\n\n-   **Weather** is the leading cause of large-scale cancellations in northern or high-altitude airports.\n\n-   **Carrier-related issues** tend to dominate in high-traffic, high-pressure hubs where airline operations are more complex.\n\n-   Different airports experience different operational pressures, and cancellation patterns reflect these localized challenges.\n\nUnderstanding these causes is crucial for both airlines and airport managers as they work to mitigate disruptions and improve travel reliability.\n\n## Daily Trend Analysis\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nq7 <- read_csv(\"q7.csv\", show_col_types = FALSE) %>%\n  mutate(\n    Num_Flights = as.numeric(Num_Flights),\n    Avg_Flights_Preceding_3_Days = as.numeric(Avg_Flights_Preceding_3_Days),\n    FlightDate = as.Date(FlightDate)\n  )\n\nq7 %>%\n  ggplot(aes(x = FlightDate)) +\n  geom_line(aes(y = Num_Flights), linewidth = 0.4, color = \"gray40\") +\n  geom_line(aes(y = Avg_Flights_Preceding_3_Days), linewidth = 0.8, color = \"steelblue\") +\n  labs(\n    title = \"Daily Flights with 3-Day Moving Average\",\n    x = \"Date\",\n    y = \"Number of flights\"\n  ) +\n  theme_bw(base_size = 12) +\n  theme(\n    plot.title = element_text(hjust = 0.5),\n    axis.text.x = element_text(angle = 45, hjust = 1)\n  )\n```\n\n::: {.cell-output-display}\n![](miniproject_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\n\n\nThe chart shows the total number of flights for each day in November, along with a 3-day moving average that smooths short-term fluctuations to reveal the overall pattern.\n\nDaily flight counts vary noticeably from day to day, reflecting operational and scheduling cycles within the airline industry. Despite these fluctuations, the 3-day moving average reveals a stable overall trend, with daily volumes consistently remaining around 20,000–21,000 flights throughout the month.\n\nA few notable dips appear in the raw daily counts, but the moving average remains steady, indicating that these sudden declines are isolated anomalies rather than early signs of a downward trend. Near the end of the month, the chart shows a modest decrease—likely due to reduced flight activity during the Thanksgiving holiday period, followed by a quick recovery.\n\nOverall, the moving-average line provides a clearer view of the underlying trend: flight activity remains strong and relatively stable across November, with only short-lived disruptions.\n\n## Conclusion\n\nThis project provides a comprehensive analysis of airline on-time performance using multiple dimensions of flight operations, including delays, early departures, airport congestion, cancelation behavior, and daily activity trends. By integrating data from several lookup tables and the main performance dataset, we are able to uncover insights that reflect both operational challenges and broader patterns in the U.S. aviation system.\n\nAcross airlines, we observe substantial variation in maximum departure delays as well as early departure behavior, indicating differences in operational efficiency, scheduling buffers, and exposure to congested routes. The weekday analysis reveals that flight volume peaks on Fridays, consistent with both business and leisure travel patterns, while mid-week days show slightly lower demand.\n\nAirport-level analysis highlights that certain airports experience significantly higher average delays than others. These findings suggest that airport-specific factors—such as weather, runway capacity, traffic volume, or geographic constraints—contribute to persistent performance differences. When examining each airline’s “worst-performing” airport, we further see how carrier networks and route structures shape delay outcomes.\n\nCancelation analysis shows that cancelations do occur in notable quantities, with weather and carrier-related issues representing the most common causes at the airports with the highest cancelation counts. This emphasizes the dual role of environmental factors and operational decision-making in flight disruptions.\n\nFinally, the daily trend visualization, using a 3-day moving average, reveals that flight activity remains relatively stable throughout the month, with occasional dips likely tied to holiday periods or short-term operational impacts. The moving average helps clarify that these fluctuations do not represent long-term declines but normal variation within a stable system.\n\nOverall, these analyses collectively demonstrate how delays and cancelations arise from the interaction between airline scheduling practices, airport capacity, weather conditions, and passenger demand patterns. The findings highlight the importance of data-driven monitoring for improving operational resilience, optimizing schedules, and enhancing traveler experience.\n",
    "supporting": [
      "miniproject_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}